### ISSUE TITLE
add labels for get_scheduleO

### ISSUE THREAD

**Issue by milandv** [p3lab/ParseIRS990#1]
For the get_scheduleO function, we should grab both the `FormAndLineReferenceDesc` as well as the `ExplanationTxt` so we know what the text is about.

**Comment by jaeyk** [comment]
@milandv Why not taking the same approach scheduleR?

**Comment by milandv** [comment]
Ah, because the data are structured differently in the XML.

For schedule R, the value of `EIN` is always the EIN of an organization that is legally related to the filing organization.

For Schedule O, the value of `ExplanationTxt` is the text answer to some other part of the filing that didn't fit in that form's space and the `FormAndLineRefereceDesc` says what part of the filing the ExplanationTxt is meant to go with. So for ScheduleO we need both those values.

@jaeyk

**Comment by jaeyk** [comment]
@milandv Thanks for the prompt reply. Almost done with resolving #1. I added the new feature and am now also adding unit testing.

**Comment by jaeyk** [comment]
Also, added 2019 IRS data as `data("idx_2019")` object.
