### ISSUE TITLE
need to account for IRS filing period

### ISSUE THREAD

**Issue by milandv** [p3lab/ParseIRS990#15]
Filings in a given year's index, 
a) can have multiple submissions for the same tax period
b) the same organization can file for multiple tax periods
c) the tax period can be from any previous year. 

Here's an example of an org from the 2019 index that has both multiple submissions on the same filing as well as filings for multiple years:

`idx_2019 %>% filter(EIN=="311810938") %>% select(EIN, TaxPeriod, SubmittedOn, ObjectId, LastUpdated)
        EIN TaxPeriod SubmittedOn           ObjectId         LastUpdated
1 311810938    201812  2019-05-21 201920849349200622 2019-06-19T01:50:03
2 311810938    201612  2019-08-23 201941639349200734 2019-09-11T19:02:20
3 311810938    201612  2019-06-14 201911429349200746 2019-06-19T01:50:03
4 311810938    201612  2019-09-24 201901759349200045 2019-12-12T23:31:50
5 311810938    201612  2019-08-09 201901529349200700 2019-12-12T23:31:50
6 311810938    201612  2019-08-10 201901519349200815 2019-12-12T23:31:50`

There are two ways we can think to approach this. 

1. "Fix" the index so that we create new index files that go by tax period. This is not a great solution both because it commits us to ongoing maintenance of those index files and because it doesn't deal with the corner case where an organization switched their filing period so has two distinct filings in the same year. (For example, 201806 and 201812). It is a fast solution though.
2. We deal with this in the functions. This is ultimately cleaner. Just requires thinking through how that should actually work in the case that an org has more than one filing year.

**Comment by jaeyk** [comment]
If there's a way we can figure this out I second that 2 is better. Also, solving this problem is a necessary condition to do panel data analysis. Ultimately, we need a series of unique ID-TIME pairs.

**Comment by milandv** [comment]
Here's an idea. 

What if `get_aws_url` returns a tibble or list with columns that are tax_period and url. Then get_990 is by default applied to that list.

Or else get_990 returns a tibble and the other functions are lapplied. Or something like that. 

Point is, we can return a list of all tax_periods and XML objects for a given EID and then apply other functions to that list. 

That might let us keep most of the architecture we have while still capturing all the tax periods for a given EIN.
