### ISSUE TITLE
need to grab descriptive texts from different fields for 990EZ

### ISSUE THREAD

**Issue by milandv** [p3lab/ParseIRS990#4]
We need to add a couple lines here for 990EZ filings. That is,

if //Return/ReturnTypeCd == 990 then what we have works:

mission description is in - //MissionDesc
program descriptions are in - //Desc (of which there may be up to 3)).

if //Return/ReturnTypeCd == 990EZ then:

mission description is in - //PrimaryExemptPurposeTxt
program descriptions are in - //DescriptionProgramSrvcAccomTxt

**Comment by jaeyk** [comment]
@milandv When you have time, label this issue.
