### ISSUE TITLE
get_value_990 needs to parse return type and find values conditional on that

### ISSUE THREAD

**Issue by milandv** [p3lab/ParseIRS990#5]
This is similar to issue #4 but for the get_value_990 function. 

The return type is in `Return/ReturnTypeCd`. This is in the first part of the xml tree. 

From there, the individual value extractions will just become conditional. 

if (return_type == "990") { get value by extracting this } else if (return_type == "990EZ") { get value by extracting this other field } 

That kind of thing.

**Comment by jaeyk** [comment]
@milandv Since you've worked on this already, do you have ein examples for 990 and 990EZ? If you can provide them, I will rewrite the code and also add testing.

**Comment by milandv** [comment]
@jaeyk  I do!

990 : 200067392
990 : 820346478

990EZ : 473779347
990EZ : 010502883

**Comment by jaeyk** [comment]
@milandv I will get this done by upcoming Monday.
