### ISSUE TITLE
get_scheduleO should return all entries in scheduleO

### ISSUE THREAD

**Issue by milandv** [p3lab/ParseIRS990#8]
Example: `get_scheduleO("061553389")` returns the first item in ScheduleO but not the others. 

See here for the full list: http://s3.amazonaws.com/irs-form-990/201911779349300991_public.xml

(the pluck(1) in the function is taking only the first)

**Comment by jaeyk** [comment]
@milandv The new commit addressed this problem and also fixed the similar problem in {ref}.
